[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
indicatif = "0.17.8"
serial2 = "0.2.24"
shlex = "1.3.0"
thiserror = "1.0.59"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
